### ISSUE TITLE
Without jailbreak, use "com.apple.CFNetowrk.plist" to capture the package

### ISSUE THREAD

**Issue by Haif-07** [doronz88/harlogger#15]
Without jailbreaking, I used some other methods to place the plist file from your project into the iPhone's path /var/mobile/Library/Preferences/, but it did not trigger the com.apple.CFNetwork.har-capture-update notification. Can using pymobiledevice3 notification trigger this notification?  

Model: iPhone XR  
Version: 17.4

**Comment by doronz88** [comment]
This is only relevant for iOS 14.x
