### ISSUE TITLE
Only works on macos?

### ISSUE THREAD

**Issue by g0dev** [doronz88/harlogger#2]
Hey, i was wondering if this works with windows too or only macos. ty

**Comment by doronz88** [comment]
The technique only depends on the device side (iOS>=14). The configurarion enables the device to report syslog messages which can be read from Windows also. For automating the sniffing into a nicer format, the script depends on `pymobiledevice3` which can be trickier for installation on Windows (requires iTunes to be installed) but should work regardless.

**Comment by g0dev** [comment]
I already installed the .deb package on my iphone 12 pro max w unc0ver using filza but i cant get work the py listener. alr installed the requeriments and the itunes .exe version but still doesnt works

**Comment by g0dev** [comment]
i get this error 
![image](https://user-images.githubusercontent.com/55219735/129073329-f4630b47-c56b-421d-8563-0f9e761aa4a7.png)

**Comment by doronz88** [comment]
This was actually a bug I created when breaking an API from `pymobiledevice3` and didn't make sure harlogger was still compatible with it. It is fixed now - just pull the recent version. Thanks for reporting!

**Comment by doronz88** [comment]
If you are having trouble making a PR I can modify it myself on a seperate branch but I'll need you to help me test it. Please PM me (doron88@gmail.com) if you prefer this option.
