### ISSUE TITLE
[Question] - jb required to sniff or only to install CFNetwork plist file?

### ISSUE THREAD

**Issue by iam-theKid** [doronz88/harlogger#3]
It was not clear to me, so, is the jb needed also to start sniffing or it is just required to setup harlogger (install the plist file and/or adjust target process)? Thanks!

**Comment by doronz88** [comment]
Without a jb you can still use harlogger to sniff the http headers but not the body

**Comment by doronz88** [comment]
If the target application is in debug mode you can still use harlogger to sniff the body also.

**Comment by iam-theKid** [comment]
Thanks buddy, all clear!
